[package]
name = "learning_comfy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = { git = "https://github.com/Sigmoidle/comfy_touch_support.git" }
